<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXKiA8O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXKiA8O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSXKiA8O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSXKiA8O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSXKiA8O\App_KernelDevDebugContainer([
    'container.build_hash' => 'SXKiA8O',
    'container.build_id' => '459dbf1f',
    'container.build_time' => 1598434467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSXKiA8O');
